<Project>
  <PropertyGroup>
    <FrameworkVersion Condition="'$(TargetFramework)' == 'net8.0'">[8.0.15,9.0.0)</FrameworkVersion>
    <FrameworkVersion Condition="'$(TargetFramework)' == 'net9.0'">[9.0.4,10.0.0)</FrameworkVersion>
    <RoslinatorVersion>[4.14.1,)</RoslinatorVersion>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="[8.0.0,)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="[8.0.0,)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="[8.0.1,)" />
  </ItemGroup>
  <ItemGroup Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="[9.0.0,)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Binder" Version="[9.0.0,)" />
    <PackageVersion Include="Microsoft.Extensions.Configuration.Json" Version="[9.0.0,)" />
  </ItemGroup>
  <ItemGroup>
  </ItemGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="[8.0.0,)" />
    <GlobalPackageReference Include="Roslynator.Analyzers" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.CodeAnalysis.Analyzers" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.CodeFixes" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.Formatting.Analyzers" Version="$(RoslinatorVersion)" />
    <GlobalPackageReference Include="Roslynator.Refactorings" Version="$(RoslinatorVersion)" />
  </ItemGroup>
</Project>