<Project>
  <Import Project="$([MSBuild]::GetPathOfFileAbove(Directory.Packages.props, $(MSBuildThisFileDirectory)..))" />
  <ItemGroup  Condition="'$(TargetFramework)' == 'net9.0'">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="[9.0.0,10.0.0)" />
  </ItemGroup>
  <ItemGroup  Condition="'$(TargetFramework)' == 'net8.0'">
    <PackageVersion Include="Microsoft.Extensions.Configuration" Version="[8.0.0,9.0.0)" />
  </ItemGroup>
  <ItemGroup>
    <GlobalPackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" />
  </ItemGroup>
</Project>