name: build

on:
  workflow_dispatch:

env:
  project_path: 'src/PetToys.TemplatedConfigurationProvider/PetToys.TemplatedConfigurationProvider.csproj'

jobs:
  test:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Install dependencies
        run: dotnet restore
      - name: Test
        run: dotnet test --no-restore --configuration Release --filter Category!=Integration
 
  build:
    needs: test
    name: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v3
        with:
          global-json-file: global.json
      - name: Install dependencies
        run: dotnet restore ${{ env.project_path }}
      - name: Build project
        run: dotnet build ${{ env.project_path }} --configuration Release --no-restore -p:Version=0.1.0-dev-321
      - name: Pack project
        run: dotnet pack ${{ env.project_path }} --configuration Release  --no-build --include-symbols -p:PackageVersion=0.1.0-dev-321
    