name: test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Setup .NET
      uses: actions/setup-dotnet@9a946fdbd5fb07b82b2f5a4466058b876ab72bb2 # v5.3.0
      with:
        global-json-file: global.json

    - name: Restore
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore --configuration Release --filter Category!=Integration