name: test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
    - main
    - dev
  pull_request:
    branches:
    - main
    - dev

jobs:
  test:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        global-json-file: global.json

    - name: Restore
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore --configuration Release --filter Category!=Integration