name: test

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
    - dev
  pull_request:
    branches:
    - dev

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: test-${{ matrix.os }}
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

    - name: Setup .NET
      uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5.4.0
      with:
        global-json-file: global.json

    - name: Restore
      run: dotnet restore

    - name: Test
      run: dotnet test --no-restore --configuration Release --filter Category!=Integration